FROM python:3.6.4

# install environment dependencies
RUN apt-get update -yqq \
&& apt-get install -yqq --no-install-recommends \
netcat \
&& apt-get -q clean
# set working directory
#
WORKDIR /app

# add app
COPY . /app
# add requirements
#COPY ./requirements.txt /usr/src/app/requirements.txt
# install requirements
RUN pip install -r requirements.txt



# add entrypoint-prod.sh
#COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh

RUN chmod +x /app/entrypoint-prod.sh 

# run server
CMD ["/app/entrypoint-prod.sh"]
#CMD python ./manage.py run -h 0.0.0.0